INSERT INTO pet_type (description) VALUES ('cachorro'), ('gato'), ('coelho');
INSERT INTO pet_size (description) VALUES ('pequeno'), ('medio'), ('grande');
INSERT INTO pet_color (description) VALUES ('preto'), ('branco'),('frajola'), ('caramelo'), ('marrom');
INSERT INTO pet_sex (description) VALUES ('femea'), ('macho'), ('indefinido');
INSERT INTO pet (nome, id_type, id_size, id_color, id_sex, idade) VALUES ('felicia', 2, 2, 1, 1,2);
INSERT INTO pet (nome, id_type, id_size, id_color, id_sex, idade) VALUES ('tom', 2, 2, 1, 2,2);
INSERT INTO pet (nome, id_type, id_size, id_color, id_sex, idade) VALUES ('frajola', 2, 2, 3, 2,2);
INSERT INTO pet (nome, id_type, id_size, id_color, id_sex, idade) VALUES ('linda', 1, 2, 4, 1,2);
INSERT INTO pet (nome, id_type, id_size, id_color, id_sex, idade) VALUES ('thor', 1, 3, 1, 2,2);
INSERT INTO pet (nome, id_type, id_size, id_color, id_sex, idade) VALUES ('bela', 1, 1, 2, 1,2);
