INSERT INTO pet_type (description) VALUES ('cachorro'), ('gato'), ('coelho');
INSERT INTO pet_size (description) VALUES ('pequeno'), ('medio'), ('grande');
INSERT INTO pet_color (description) VALUES ('preto'), ('branco'),('frajola'), ('caramelo'), ('marrom');
INSERT INTO pet_sex (description) VALUES ('feminino'), ('masculino'), ('indefinido');
INSERT INTO pet (name, id_type, id_size, id_color, id_sex, age, was_adopted ) VALUES ('felicia', 2, 2, 1, 1,2, false);
INSERT INTO pet (name, id_type, id_size, id_color, id_sex, age, was_adopted ) VALUES ('tom', 2, 2, 1, 2,2, false);
INSERT INTO pet (name, id_type, id_size, id_color, id_sex, age, was_adopted ) VALUES ('frajola', 2, 2, 3, 2,2, false );
INSERT INTO pet (name, id_type, id_size, id_color, id_sex, age, was_adopted) VALUES ('linda', 1, 2, 4, 1,2, false);
INSERT INTO pet (name, id_type, id_size, id_color, id_sex, age, was_adopted ) VALUES ('thor', 1, 3, 1, 2,2, false );
INSERT INTO pet (name, id_type, id_size, id_color, id_sex, age, was_adopted ) VALUES ('bela', 1, 1, 2, 1,2, false );
